/* Generated By:JJTree: Do not edit this line. ASTAssertionExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser.jjt;

public
class ASTAssertionExpression extends SimpleNode {
  public ASTAssertionExpression(int id) {
    super(id);
  }

  public ASTAssertionExpression(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=af3c7ec6a35180bb108e821a673a1a17 (do not edit this line) */
