/* Generated By:JJTree: Do not edit this line. ASTContextClassList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser.jjt;

public
class ASTContextClassList extends SimpleNode {
  public ASTContextClassList(int id) {
    super(id);
  }

  public ASTContextClassList(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=710f926e2cf74f0e9631dd18840ee5c5 (do not edit this line) */
