/* Generated By:JJTree: Do not edit this line. ASTCheckExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser.jjt;

public
class ASTCheckExpression extends SimpleNode {
  public ASTCheckExpression(int id) {
    super(id);
  }

  public ASTCheckExpression(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=56321df358c95660eeaa7cd4436f97f3 (do not edit this line) */
