/* Generated By:JJTree: Do not edit this line. ASTDerivationBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser.jjt;

public
class ASTDerivationBody extends SimpleNode {
  public ASTDerivationBody(int id) {
    super(id);
  }

  public ASTDerivationBody(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b81040093bef24755e0291ac3ffd1a51 (do not edit this line) */
