/* Generated By:JJTree: Do not edit this line. ASTDerivationBodyExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser.jjt;

public
class ASTDerivationBodyExpression extends SimpleNode {
  public ASTDerivationBodyExpression(int id) {
    super(id);
  }

  public ASTDerivationBodyExpression(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b82abf1daf78b259d6d9f15fa316d400 (do not edit this line) */
