/* Generated By:JJTree: Do not edit this line. ASTErrorCodeExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser.jjt;

public class ASTErrorCodeExpression extends SimpleNode {
	
	private ASTPath errorPath;
	
	private ASTSignature errorCode;
	
	public ASTErrorCodeExpression(int id) {
		super(id);
	}

	public ASTErrorCodeExpression(Parser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(ParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public ASTPath getErrorPath() {
		return errorPath;
	}

	public void setErrorPath(ASTPath errorPath) {
		this.errorPath = errorPath;
	}

	public ASTSignature getErrorCode() {
		return errorCode;
	}

	public void setErrorCode(ASTSignature errorCode) {
		this.errorCode = errorCode;
	}
}
/*
 * JavaCC - OriginalChecksum=d1d6039c557c8c2128f78ac3ecc5de2e (do not edit this
 * line)
 */
