/* Generated By:JJTree: Do not edit this line. ASTExpressionRoot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser.jjt;

public
class ASTExpressionRoot extends SimpleNode {
  public ASTExpressionRoot(int id) {
    super(id);
  }

  public ASTExpressionRoot(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e7bc31d43b82eea538bd1f9c73a32c5c (do not edit this line) */
