/* Generated By:JJTree: Do not edit this line. ASTLeftFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser.jjt;

public class ASTLeftFunction extends SimpleNode {

	private String domain;
	private String field;
	private int length;
	
	public ASTLeftFunction(int id) {
		super(id);
	}

	public ASTLeftFunction(Parser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(ParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
	
	public String getDomain() {
		return domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public String getField() {
		return field;
	}

	public void setField(String field) {
		this.field = field;
	}

	public int getLength() {
		return length;
	}

	public void setLength(int length) {
		this.length = length;
	}
}
/*
 * JavaCC - OriginalChecksum=dbd37ab2ce16fd9f93f781ef69f43c2a (do not edit this
 * line)
 */
