/* Generated By:JJTree: Do not edit this line. ASTLogicalBodyExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser.jjt;

public
class ASTLogicalBodyExpression extends SimpleNode {
  public ASTLogicalBodyExpression(int id) {
    super(id);
  }

  public ASTLogicalBodyExpression(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d84a45856cbf0084114725264176b7e6 (do not edit this line) */
