/* Generated By:JJTree: Do not edit this line. ASTNotEmptyExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser.jjt;

public
class ASTNotEmptyExpression extends SimpleNode {
  public ASTNotEmptyExpression(int id) {
    super(id);
  }

  public ASTNotEmptyExpression(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7e79ac9986ce20f720eeebcdb33c4d84 (do not edit this line) */
