/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package com.cathysoft.ruleparser.jjt;

public interface ParserTreeConstants
{
  public int JJTEXPRESSIONROOT = 0;
  public int JJTCONTEXTCLASSLIST = 1;
  public int JJTNOTEMPTYEXPRESSION = 2;
  public int JJTCHECKEXPRESSION = 3;
  public int JJTASSERTIONEXPRESSION = 4;
  public int JJTDERIVATIONEXPRESSION = 5;
  public int JJTLOGICALEXPRESSION = 6;
  public int JJTDERIVATIONBODY = 7;
  public int JJTOPERATOREXPRESSION = 8;
  public int JJTFUNCTIONEXPRESSION = 9;
  public int JJTEMPTYFUNCTION = 10;
  public int JJTSIZEFUNCTION = 11;
  public int JJTMIDFUNCTION = 12;
  public int JJTRIGHTFUNCTION = 13;
  public int JJTLEFTFUNCTION = 14;
  public int JJTPATH = 15;
  public int JJTSIGNATURE = 16;


  public String[] jjtNodeName = {
    "ExpressionRoot",
    "ContextClassList",
    "NotEmptyExpression",
    "CheckExpression",
    "AssertionExpression",
    "DerivationExpression",
    "LogicalExpression",
    "DerivationBody",
    "OperatorExpression",
    "FunctionExpression",
    "EmptyFunction",
    "SizeFunction",
    "MidFunction",
    "RightFunction",
    "LeftFunction",
    "Path",
    "Signature",
  };
}
/* JavaCC - OriginalChecksum=1485702195c0fc3fee901f355c4449c9 (do not edit this line) */
