/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 5.0 */
package com.cathysoft.ruleparser.jjt;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTExpressionRoot node, Object data);
  public Object visit(ASTClassList node, Object data);
  public Object visit(ASTNotEmptyExpression node, Object data);
  public Object visit(ASTCheckExpression node, Object data);
  public Object visit(ASTLogicalExpression node, Object data);
  public Object visit(ASTDerivationExpression node, Object data);
  public Object visit(ASTLogicalBodyExpression node, Object data);
  public Object visit(ASTDerivationBodyExpression node, Object data);
  public Object visit(ASTOperatorExpression node, Object data);
  public Object visit(ASTDomainExpression node, Object data);
  public Object visit(ASTFunctionExpression node, Object data);
  public Object visit(ASTEmptyFunction node, Object data);
  public Object visit(ASTSizeFunction node, Object data);
  public Object visit(ASTMidFunction node, Object data);
  public Object visit(ASTRightFunction node, Object data);
  public Object visit(ASTLeftFunction node, Object data);
}
/* JavaCC - OriginalChecksum=ffaebf237b896f34dc0ad028c08d7b8e (do not edit this line) */
