/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package com.cathysoft.ruleparser.jjt;

public interface ParserTreeConstants
{
  public int JJTEXPRESSIONROOT = 0;
  public int JJTCLASSLIST = 1;
  public int JJTNOTEMPTYEXPRESSION = 2;
  public int JJTCHECKEXPRESSION = 3;
  public int JJTLOGICALEXPRESSION = 4;
  public int JJTDERIVATIONEXPRESSION = 5;
  public int JJTLOGICALBODYEXPRESSION = 6;
  public int JJTDERIVATIONBODYEXPRESSION = 7;
  public int JJTOPERATOREXPRESSION = 8;
  public int JJTDOMAINEXPRESSION = 9;
  public int JJTFUNCTIONEXPRESSION = 10;
  public int JJTEMPTYFUNCTION = 11;
  public int JJTSIZEFUNCTION = 12;
  public int JJTMIDFUNCTION = 13;
  public int JJTRIGHTFUNCTION = 14;
  public int JJTLEFTFUNCTION = 15;


  public String[] jjtNodeName = {
    "ExpressionRoot",
    "ClassList",
    "NotEmptyExpression",
    "CheckExpression",
    "LogicalExpression",
    "DerivationExpression",
    "LogicalBodyExpression",
    "DerivationBodyExpression",
    "OperatorExpression",
    "DomainExpression",
    "FunctionExpression",
    "EmptyFunction",
    "SizeFunction",
    "MidFunction",
    "RightFunction",
    "LeftFunction",
  };
}
/* JavaCC - OriginalChecksum=ac9404f373812de2bb999c5966756cc5 (do not edit this line) */
