/* Generated By:JJTree: Do not edit this line. ASTCheckExpession.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser;

public
class ASTCheckExpession extends SimpleNode {
  public ASTCheckExpession(int id) {
    super(id);
  }

  public ASTCheckExpession(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b191146441acff4af89531d6a75947b (do not edit this line) */
