/* Generated By:JJTree: Do not edit this line. ASTClassList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser;

public
class ASTClassList extends SimpleNode {
  public ASTClassList(int id) {
    super(id);
  }

  public ASTClassList(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b75e6db99652136eacc244b21b9a2d3c (do not edit this line) */
