/* Generated By:JJTree: Do not edit this line. ASTCheckExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser;

public
class ASTCheckExpression extends SimpleNode {
  public ASTCheckExpression(int id) {
    super(id);
  }

  public ASTCheckExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ccdc5bc71dff8f082bf09508d1864ba5 (do not edit this line) */
