/* Generated By:JJTree: Do not edit this line. ASTExpressionRoot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser;

public
class ASTExpressionRoot extends SimpleNode {
  public ASTExpressionRoot(int id) {
    super(id);
  }

  public ASTExpressionRoot(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=de1d4b6146cd2f58f2ce981e7ad8afd0 (do not edit this line) */
