/* Generated By:JJTree: Do not edit this line. ASTNotEmptyExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.cathysoft.ruleparser;

public
class ASTNotEmptyExpression extends SimpleNode {
  public ASTNotEmptyExpression(int id) {
    super(id);
  }

  public ASTNotEmptyExpression(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c9e1fe4ac0020338dba967d26ad2ac04 (do not edit this line) */
