/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package com.cathysoft.ruleparser;

public interface ParserTreeConstants
{
  public int JJTEXPRESSIONROOT = 0;
  public int JJTCLASSLIST = 1;
  public int JJTNOTEMPTYEXPRESSION = 2;
  public int JJTCHECKEXPRESSION = 3;


  public String[] jjtNodeName = {
    "ExpressionRoot",
    "ClassList",
    "NotEmptyExpression",
    "CheckExpression",
  };
}
/* JavaCC - OriginalChecksum=eeb667d55f76df9504b652801bfb4e77 (do not edit this line) */
